/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as AuthoringRouteImport } from './routes/authoring'
import { Route as AvatarRouteImport } from './routes/avatar'
import { Route as InteractiveRouteImport } from './routes/interactive'
import { Route as CourseWorkspaceIdRouteImport } from './routes/course.$workspaceId'
import { Route as KataNameRouteImport } from './routes/kata.$name'
import { Route as SessionSessionIdRouteImport } from './routes/session.$sessionId'
import { Route as CourseWorkspaceIdIndexRouteImport } from './routes/course.$workspaceId.index'
import { Route as CourseWorkspaceIdCourseIdLessonLessonIdRouteImport } from './routes/course.$workspaceId.$courseId.lesson.$lessonId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthoringRoute = AuthoringRouteImport.update({
  id: '/authoring',
  path: '/authoring',
  getParentRoute: () => rootRouteImport,
} as any)
const AvatarRoute = AvatarRouteImport.update({
  id: '/avatar',
  path: '/avatar',
  getParentRoute: () => rootRouteImport,
} as any)
const InteractiveRoute = InteractiveRouteImport.update({
  id: '/interactive',
  path: '/interactive',
  getParentRoute: () => rootRouteImport,
} as any)
const CourseWorkspaceIdRoute = CourseWorkspaceIdRouteImport.update({
  id: '/course/$workspaceId',
  path: '/course/$workspaceId',
  getParentRoute: () => rootRouteImport,
} as any)
const KataNameRoute = KataNameRouteImport.update({
  id: '/kata/$name',
  path: '/kata/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionSessionIdRoute = SessionSessionIdRouteImport.update({
  id: '/session/$sessionId',
  path: '/session/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const CourseWorkspaceIdIndexRoute = CourseWorkspaceIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CourseWorkspaceIdRoute,
} as any)
const CourseWorkspaceIdCourseIdLessonLessonIdRoute =
  CourseWorkspaceIdCourseIdLessonLessonIdRouteImport.update({
    id: '/$courseId/lesson/$lessonId',
    path: '/$courseId/lesson/$lessonId',
    getParentRoute: () => CourseWorkspaceIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/authoring': typeof AuthoringRoute
  '/avatar': typeof AvatarRoute
  '/interactive': typeof InteractiveRoute
  '/course/$workspaceId': typeof CourseWorkspaceIdRouteWithChildren
  '/kata/$name': typeof KataNameRoute
  '/session/$sessionId': typeof SessionSessionIdRoute
  '/course/$workspaceId/': typeof CourseWorkspaceIdIndexRoute
  '/course/$workspaceId/$courseId/lesson/$lessonId': typeof CourseWorkspaceIdCourseIdLessonLessonIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/authoring': typeof AuthoringRoute
  '/avatar': typeof AvatarRoute
  '/interactive': typeof InteractiveRoute
  '/kata/$name': typeof KataNameRoute
  '/session/$sessionId': typeof SessionSessionIdRoute
  '/course/$workspaceId': typeof CourseWorkspaceIdIndexRoute
  '/course/$workspaceId/$courseId/lesson/$lessonId': typeof CourseWorkspaceIdCourseIdLessonLessonIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/authoring': typeof AuthoringRoute
  '/avatar': typeof AvatarRoute
  '/interactive': typeof InteractiveRoute
  '/course/$workspaceId': typeof CourseWorkspaceIdRouteWithChildren
  '/kata/$name': typeof KataNameRoute
  '/session/$sessionId': typeof SessionSessionIdRoute
  '/course/$workspaceId/': typeof CourseWorkspaceIdIndexRoute
  '/course/$workspaceId/$courseId/lesson/$lessonId': typeof CourseWorkspaceIdCourseIdLessonLessonIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/authoring'
    | '/avatar'
    | '/interactive'
    | '/course/$workspaceId'
    | '/kata/$name'
    | '/session/$sessionId'
    | '/course/$workspaceId/'
    | '/course/$workspaceId/$courseId/lesson/$lessonId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/authoring'
    | '/avatar'
    | '/interactive'
    | '/kata/$name'
    | '/session/$sessionId'
    | '/course/$workspaceId'
    | '/course/$workspaceId/$courseId/lesson/$lessonId'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/authoring'
    | '/avatar'
    | '/interactive'
    | '/course/$workspaceId'
    | '/kata/$name'
    | '/session/$sessionId'
    | '/course/$workspaceId/'
    | '/course/$workspaceId/$courseId/lesson/$lessonId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AuthoringRoute: typeof AuthoringRoute
  AvatarRoute: typeof AvatarRoute
  InteractiveRoute: typeof InteractiveRoute
  CourseWorkspaceIdRoute: typeof CourseWorkspaceIdRouteWithChildren
  KataNameRoute: typeof KataNameRoute
  SessionSessionIdRoute: typeof SessionSessionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authoring': {
      id: '/authoring'
      path: '/authoring'
      fullPath: '/authoring'
      preLoaderRoute: typeof AuthoringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/avatar': {
      id: '/avatar'
      path: '/avatar'
      fullPath: '/avatar'
      preLoaderRoute: typeof AvatarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interactive': {
      id: '/interactive'
      path: '/interactive'
      fullPath: '/interactive'
      preLoaderRoute: typeof InteractiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/course/$workspaceId': {
      id: '/course/$workspaceId'
      path: '/course/$workspaceId'
      fullPath: '/course/$workspaceId'
      preLoaderRoute: typeof CourseWorkspaceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kata/$name': {
      id: '/kata/$name'
      path: '/kata/$name'
      fullPath: '/kata/$name'
      preLoaderRoute: typeof KataNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session/$sessionId': {
      id: '/session/$sessionId'
      path: '/session/$sessionId'
      fullPath: '/session/$sessionId'
      preLoaderRoute: typeof SessionSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/course/$workspaceId/': {
      id: '/course/$workspaceId/'
      path: '/'
      fullPath: '/course/$workspaceId/'
      preLoaderRoute: typeof CourseWorkspaceIdIndexRouteImport
      parentRoute: typeof CourseWorkspaceIdRoute
    }
    '/course/$workspaceId/$courseId/lesson/$lessonId': {
      id: '/course/$workspaceId/$courseId/lesson/$lessonId'
      path: '/$courseId/lesson/$lessonId'
      fullPath: '/course/$workspaceId/$courseId/lesson/$lessonId'
      preLoaderRoute: typeof CourseWorkspaceIdCourseIdLessonLessonIdRouteImport
      parentRoute: typeof CourseWorkspaceIdRoute
    }
  }
}

interface CourseWorkspaceIdRouteChildren {
  CourseWorkspaceIdIndexRoute: typeof CourseWorkspaceIdIndexRoute
  CourseWorkspaceIdCourseIdLessonLessonIdRoute: typeof CourseWorkspaceIdCourseIdLessonLessonIdRoute
}

const CourseWorkspaceIdRouteChildren: CourseWorkspaceIdRouteChildren = {
  CourseWorkspaceIdIndexRoute: CourseWorkspaceIdIndexRoute,
  CourseWorkspaceIdCourseIdLessonLessonIdRoute:
    CourseWorkspaceIdCourseIdLessonLessonIdRoute,
}

const CourseWorkspaceIdRouteWithChildren =
  CourseWorkspaceIdRoute._addFileChildren(CourseWorkspaceIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AuthoringRoute: AuthoringRoute,
  AvatarRoute: AvatarRoute,
  InteractiveRoute: InteractiveRoute,
  CourseWorkspaceIdRoute: CourseWorkspaceIdRouteWithChildren,
  KataNameRoute: KataNameRoute,
  SessionSessionIdRoute: SessionSessionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
